name: 'slack-actions'
description: 'Posts PR notifications to slack'
inputs:
  slack-bot-token:
    description: 'API token to post messages to slack'
    required: true
  channel-id:
    description: 'Channel that manages PR notifications'
    required: true
  action:
    description: 'Slack action to take'
    required: true
  message:
    description: 'Slack message template'
    required: true
  string-matcher:
    description: 'Message string matcher to find first message containing'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
